name: Create Release
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release
      # if: ${{ github.ref == 'refs/heads/main' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.2
        release_name: Release v1.0.2
        body: |
          Add support for RT-Thread 4.0.5
        draft: false
        prerelease: false